server:
  port: 1001

spring:
  redis:
    port: 6379
    password:
    host: test-scdb.nimble.cn
    lettuce:
      pool:
        max-active: 10 #最大连接数
        max-idle: 6 #最大空闲数
        min-idle: 2 #最小空闲数
    timeout: 5000 #连接超时
    database: 10

#spring:
#  redis:
#    port: 6379
#    password: 111111
#    host: test-scdb.nimble.cn
#    jedis:
#      pool:
#        max-idle: 6 #最大空闲数
#        max-active: 10 #最大连接数
#        min-idle: 2 #最小空闲数
#    timeout: 2000 #连接超时
#    database: 10

logging:
  config: classpath:logback-spring.xml
