server:
  port: 1001

spring:
  redis:
    port: 6379
    password:
    host: 47.107.107.227
    lettuce:
      pool:
        max-active: 10
        max-idle: 6
        min-idle: 2
    timeout: 5000
    database: 10

#spring:
#  redis:
#    port: 6379
#    password:
#    host: test-scdb.nimble.cn
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 6
#        min-idle: 2
#    timeout: 5000
#    database: 10

#spring:
#  redis:
#    port: 6379
#    password:
#    host: test-scdb.nimble.cn
#    jedis:
#      pool:
#        max-idle: 6
#        max-active: 10
#        min-idle: 2
#    timeout: 5000
#    database: 10

logging:
  config: classpath:logback-spring.xml
